language: node_js

node_js:
  - "9"

services:
  - docker

# env:
#   global:
  

before_install:
  - npm i -g bower npm@latest @angular/cli nyc

install:
  - npm i 

script: 
  - npm test 
  # - npm run lint

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master  
  